version: '2'
services:
  bot:
    build: .
    ports:
      - '127.0.0.1:13000:3000'
    environment:
      - TZ=Europe/Berlin
    env_file: .env
    volumes:
      - ./active:/usr/src/trades
      - ./completed:/usr/src/complete_trades
      - ./config:/usr/src/configs:ro
    restart: always
